[project]
name = "PA7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium[box2d,other]>=1.1.1",
    "stable-baselines3[extra]>=2.6.0",
    "swig>=4.3.0",
    "wandb>=0.19.9",
]
